### ISSUE TITLE
Assignments do not show up for annotation

### ISSUE THREAD

**Issue by johanneskiesel** [webis-de/mturk-manager#18]
When I select assignments to annotate, nothing shows up in the view:

![image](https://user-images.githubusercontent.com/187193/53157219-5440bd80-35c1-11e9-9021-8a69c20704cb.png)

The dev tools show that it looks for a "http://127.0.0.1:8000/static/mturk_manager/js/dist/index_annotate.js", which gets a 404. I found that a file of the same name at "http://127.0.0.1:8000/static/mturk_manager/js/annotate/index_annotate.js" (with "annotate" instead of "dist")... did things move?

**Comment by Kritten** [comment]
Fixed with f38c2e012176df9f36a2445afd1c4440aca24097
