### ISSUE TITLE
Sort batches by creation date

### ISSUE THREAD

**Issue by JaniTomati** [webis-de/mturk-manager#22]
After working with the manager for quite a bit now I noticed that it would be much nicer if the entries in the batch view (also maybe in the assignment view) would be sorted by creation date, i.e. from newest to oldest. 

By default it sorts by name in the batches view but every time I use that view I sort after creation to see the progress of my newest assignments. 
Sorting by name will quickly get confusing if there is no pattern to the naming. Especially if you test a lot in the sandbox. 

Of course this could be a user specific problem, but I can imagine that other people could face the same problem. :-)

**Comment by Kritten** [comment]
This is fixed in commit aa86d9ec6a3d6c2621b60cbd6bc54807e9d2d9f8 but still on the development branch.
I will merge it in the master in the next few days.
The commit even the pagination-information (number of rows per page, sort by, order) of all the different tables on the page
