### ISSUE TITLE
Costs calculation below current balance does not seem right

### ISSUE THREAD

**Issue by JaniTomati** [webis-de/mturk-manager#27]
I might be wrong but to me the costs calculation below the current balance in the finances view does not seem right. But I am also not quite sure what those numbers mean in connection to the table. 

Max costs it shows 99.80$ which are also the max costs for my most current batch. The costs so far shows 52.10$ and I don't really know where that number comes from... 

Overall, I don't know what to make of the numbers, but it could be because I don't understand what they are supposed to mean if they're not connected to a batch instance.

**Comment by Kritten** [comment]
I agree, the numbers need some explanation.
I'll work on this
